schema_version = "1.0.0"

id = "two_point_perspective"
version = "0.0.2"
name = "Two-Point Perspective"
tagline = "Replaces the active camera with a two-point perspective one"
maintainer = "Athina Syntychaki <athina.syntychaki@gmail.com>"
type = "add-on"

tags = ["Camera"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
"2025 Athina Syntychaki"
]


[build]

paths_exclude_pattern = [
"__pycache__/",
"/.git/",
"/*.zip",
]